/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Biblioteca;

/**
 *
 * @author aleja
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu1 = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuLibro = new javax.swing.JMenuItem();
        mnuReserva = new javax.swing.JMenuItem();
        mnuPrestamo = new javax.swing.JMenuItem();
        mnuDevolucion = new javax.swing.JMenuItem();
        mnuMulta = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        Jmenu1.setText("Archivos");

        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(this::mnuUsuarioActionPerformed);
        Jmenu1.add(mnuUsuario);

        mnuLibro.setText("Libro");
        mnuLibro.addActionListener(this::mnuLibroActionPerformed);
        Jmenu1.add(mnuLibro);

        mnuReserva.setText("Reserva");
        mnuReserva.addActionListener(this::mnuReservaActionPerformed);
        Jmenu1.add(mnuReserva);

        mnuPrestamo.setText("Prestamo");
        mnuPrestamo.addActionListener(this::mnuPrestamoActionPerformed);
        Jmenu1.add(mnuPrestamo);

        mnuDevolucion.setText("Devolucion");
        mnuDevolucion.addActionListener(this::mnuDevolucionActionPerformed);
        Jmenu1.add(mnuDevolucion);

        mnuMulta.setText("Multa");
        mnuMulta.addActionListener(this::mnuMultaActionPerformed);
        Jmenu1.add(mnuMulta);

        mnuReporte.setText("Reporte");
        mnuReporte.addActionListener(this::mnuReporteActionPerformed);
        Jmenu1.add(mnuReporte);

        jMenuBar1.add(Jmenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario modelo = new Usuario();
        SentenciasUsuario consultas = new SentenciasUsuario();
        frmUsuario vista = new frmUsuario();
        CtrlUsuario controlador = new CtrlUsuario(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibroActionPerformed
        // TODO add your handling code here:
        Libro modelo = new Libro();
        SentenciasLibro consultas = new SentenciasLibro();
        frmLibro vista = new frmLibro();
        CtrlLibro controlador = new CtrlLibro(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuLibroActionPerformed

    private void mnuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservaActionPerformed
        // TODO add your handling code here:
        Reserva modelo = new Reserva();
        SentenciasReserva consultas = new SentenciasReserva();
        frmReserva vista = new frmReserva();
        CtrlReserva controlador = new CtrlReserva(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuReservaActionPerformed

    private void mnuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrestamoActionPerformed
        // TODO add your handling code here:
        Prestamo modelo = new Prestamo();
        SentenciasPrestamo consultas = new SentenciasPrestamo();
        frmPrestamo vista = new frmPrestamo();
        CtrlPrestamo controlador = new CtrlPrestamo(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuPrestamoActionPerformed

    private void mnuDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDevolucionActionPerformed
        // TODO add your handling code here:
        Devolucion modelo = new Devolucion();
        SentenciasDevolucion consultas = new SentenciasDevolucion();
        frmDevolucion vista = new frmDevolucion();
        CtrlDevolucion controlador = new CtrlDevolucion(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuDevolucionActionPerformed

    private void mnuMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMultaActionPerformed
        // TODO add your handling code here:
        Multa modelo = new Multa();
        SentenciasMulta consultas = new SentenciasMulta();
        frmMulta vista = new frmMulta();
        CtrlMulta controlador = new CtrlMulta(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuMultaActionPerformed

    private void mnuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteActionPerformed
        // TODO add your handling code here:
        Reporte modelo = new Reporte();
        SentenciasReporte consultas = new SentenciasReporte();
        frmReporte vista = new frmReporte();
        CtrlReporte controlador = new CtrlReporte(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuDevolucion;
    public javax.swing.JMenuItem mnuLibro;
    private javax.swing.JMenuItem mnuMulta;
    private javax.swing.JMenuItem mnuPrestamo;
    private javax.swing.JMenuItem mnuReporte;
    public javax.swing.JMenuItem mnuReserva;
    public javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
