/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Biblioteca;

/**
 *
 * @author aleja
 */

import Controlador.CtrlBuscarLibro;
import Controlador.CtrlUsuario;
import Controlador.CtrlLibro;
import Controlador.CtrlReserva;
import Controlador.CtrlPrestamo;
import Controlador.CtrlDevolucion;
import Controlador.CtrlHistorial;
import Controlador.CtrlMulta;
import Controlador.CtrlReporte;
import Controlador.CtrlReportes;
import Modelo.Usuario;
import Modelo.SentenciasUsuario;
import Modelo.Libro;
import Modelo.SentenciasLibro;
import Modelo.Reserva;
import Modelo.SentenciasReserva;
import Modelo.Prestamo;
import Modelo.SentenciasPrestamo;
import Modelo.Devolucion;
import Modelo.SentenciasDevolucion;
import Modelo.Multa;
import Modelo.SentenciasMulta;
import Modelo.Reporte;
import Modelo.SentenciasReporte;
import Vista.frmBuscarLibro;
import Vista.frmUsuario;
import Vista.frmLibro;
import Vista.frmReserva;
import Vista.frmPrestamo;
import Vista.frmDevolucion;
import Vista.frmHistorial;
import Vista.frmMulta;
import Vista.frmReporte;
import Vista.frmReportes;
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu1 = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuLibro = new javax.swing.JMenuItem();
        mnuReserva = new javax.swing.JMenuItem();
        mnuPrestamo = new javax.swing.JMenuItem();
        mnuDevolucion = new javax.swing.JMenuItem();
        mnuMulta = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenuItem();
        mnuHistorial = new javax.swing.JMenuItem();
        mnuBuscarLibro = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LibraryScene_Final_Animated.gif"))); // NOI18N

        Jmenu1.setText("Archivos");

        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(this::mnuUsuarioActionPerformed);
        Jmenu1.add(mnuUsuario);

        mnuLibro.setText("Libro");
        mnuLibro.addActionListener(this::mnuLibroActionPerformed);
        Jmenu1.add(mnuLibro);

        mnuReserva.setText("Reserva");
        mnuReserva.addActionListener(this::mnuReservaActionPerformed);
        Jmenu1.add(mnuReserva);

        mnuPrestamo.setText("Prestamo");
        mnuPrestamo.addActionListener(this::mnuPrestamoActionPerformed);
        Jmenu1.add(mnuPrestamo);

        mnuDevolucion.setText("Devolucion");
        mnuDevolucion.addActionListener(this::mnuDevolucionActionPerformed);
        Jmenu1.add(mnuDevolucion);

        mnuMulta.setText("Multa");
        mnuMulta.addActionListener(this::mnuMultaActionPerformed);
        Jmenu1.add(mnuMulta);

        mnuReporte.setText("Reporte");
        mnuReporte.addActionListener(this::mnuReporteActionPerformed);
        Jmenu1.add(mnuReporte);

        mnuHistorial.setText("Historial");
        mnuHistorial.addActionListener(this::mnuHistorialActionPerformed);
        Jmenu1.add(mnuHistorial);

        mnuBuscarLibro.setText("Buscar Libro");
        mnuBuscarLibro.addActionListener(this::mnuBuscarLibroActionPerformed);
        Jmenu1.add(mnuBuscarLibro);

        mnuReportes.setText("Reportes");
        mnuReportes.addActionListener(this::mnuReportesActionPerformed);
        Jmenu1.add(mnuReportes);

        jMenuBar1.add(Jmenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario modelo = new Usuario();
        SentenciasUsuario consultas = new SentenciasUsuario();
        frmUsuario vista = new frmUsuario();
        CtrlUsuario controlador = new CtrlUsuario(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibroActionPerformed
        // TODO add your handling code here:
        Libro modelo = new Libro();
        SentenciasLibro consultas = new SentenciasLibro();
        frmLibro vista = new frmLibro();
        CtrlLibro controlador = new CtrlLibro(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuLibroActionPerformed

    private void mnuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservaActionPerformed
        // TODO add your handling code here:
        Reserva modelo = new Reserva();
        SentenciasReserva consultas = new SentenciasReserva();
        frmReserva vista = new frmReserva();
        CtrlReserva controlador = new CtrlReserva(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuReservaActionPerformed

    private void mnuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrestamoActionPerformed
        // TODO add your handling code here:
        Prestamo modelo = new Prestamo();
        SentenciasPrestamo consultas = new SentenciasPrestamo();
        frmPrestamo vista = new frmPrestamo();
        CtrlPrestamo controlador = new CtrlPrestamo(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuPrestamoActionPerformed

    private void mnuDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDevolucionActionPerformed
        // TODO add your handling code here:
        Devolucion modelo = new Devolucion();
        SentenciasDevolucion consultas = new SentenciasDevolucion();
        frmDevolucion vista = new frmDevolucion();
        CtrlDevolucion controlador = new CtrlDevolucion(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuDevolucionActionPerformed

    private void mnuMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMultaActionPerformed
        // TODO add your handling code here:
        Multa modelo = new Multa();
        SentenciasMulta consultas = new SentenciasMulta();
        frmMulta vista = new frmMulta();
        CtrlMulta controlador = new CtrlMulta(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuMultaActionPerformed

    private void mnuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteActionPerformed
        // TODO add your handling code here:
        Reporte modelo = new Reporte();
        SentenciasReporte consultas = new SentenciasReporte();
        frmReporte vista = new frmReporte();
        CtrlReporte controlador = new CtrlReporte(modelo, consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuReporteActionPerformed

    private void mnuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHistorialActionPerformed
        // TODO add your handling code here:
        SentenciasPrestamo consultas = new SentenciasPrestamo();
        frmHistorial vista = new frmHistorial();
        CtrlHistorial controlador = new CtrlHistorial(consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuHistorialActionPerformed

    private void mnuBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarLibroActionPerformed
        // TODO add your handling code here:
        SentenciasLibro consultas = new SentenciasLibro();
        frmBuscarLibro vista = new frmBuscarLibro();
        CtrlBuscarLibro controlador = new CtrlBuscarLibro(consultas, vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuBuscarLibroActionPerformed

    private void mnuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportesActionPerformed
        // TODO add your handling code here:
        frmReportes vista = new frmReportes();
        CtrlReportes controlador = new CtrlReportes(vista);
        controlador.inicio();
    }//GEN-LAST:event_mnuReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }
    
    public void configurarRol(String rol) {
        String rolMinuscula = rol.toLowerCase();
        if (rolMinuscula.contains("admin")) {
            //el administrador ve todas las opciones, no se oculta nada
        } else if (rolMinuscula.contains("bibliotecario")) {
            mnuUsuario.setVisible(false);
            mnuReporte.setVisible(false);
            mnuReportes.setVisible(false);
        } else {
            //estudiante, solo puede buscar, reservar y ver su historial
            mnuUsuario.setVisible(false);
            mnuLibro.setVisible(false);
            mnuPrestamo.setVisible(false);
            mnuDevolucion.setVisible(false);
            mnuMulta.setVisible(false);
            mnuReporte.setVisible(false);
            mnuReportes.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuBuscarLibro;
    public javax.swing.JMenuItem mnuDevolucion;
    private javax.swing.JMenuItem mnuHistorial;
    public javax.swing.JMenuItem mnuLibro;
    public javax.swing.JMenuItem mnuMulta;
    public javax.swing.JMenuItem mnuPrestamo;
    public javax.swing.JMenuItem mnuReporte;
    private javax.swing.JMenuItem mnuReportes;
    public javax.swing.JMenuItem mnuReserva;
    public javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
